[package]
name = "progenitor-characters"
description = "Character entity, commands, validators, importers, exporter, page"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
progenitor-core = { workspace = true }
progenitor-content = { workspace = true }
progenitor-points = { workspace = true }
progenitor-dna = { workspace = true }
progenitor-ui = { workspace = true }
